# Generated by Django 4.0.4 on 2022-05-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_profile_email_add_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
